### ISSUE TITLE
Option to declare types in global scope (no module)

### ISSUE THREAD

**Issue by flcdrg** [madskristensen/TypeScriptDefinitionGenerator#11]
### Description
I would like the option to be able to generate type declarations that are not wrapped in a module, but rather are declared in global scope. 

I would use this in combination with #10 (in particular to interop with the Microsoft.ClearScript library)

**Comment by nhammadi** [comment]
@madskristensen do you think it's a valid request. I can create a pull request for this feature if you want ?

**Comment by madskristensen** [comment]
Perhaps. Does it make sense to wrap any of the generated types in modules to begin with? Maybe my initial design was flawed in this aspect?

Btw @nhammadi you don't need to send PRs anymore. I've made you an admin of the project :)

**Comment by styfle** [comment]
Could this be changed by an Attribute? I'm not sure if you can add an attribute to a namespace but you can do it for a class.


```cs
    [TsModuleName("cards")]
    public class PendingCard
    {
        [JsonProperty("hasBeenUpdated")]
        public bool HasBeenUpdated { get; set; }
    }
```

```ts
    declare module cards {
        interface PendingCard {
             hasBeenUpdated: boolean;
        }
    }
```

If the `TsModuleName` is the empty string, then it is part of the global scope. If the attribute is missing, then default to `server` to keep it backwards compatible.

**Comment by raboud** [comment]
This already works but probably needs to documented.

adding 
```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

[System.AttributeUsage(AttributeTargets.Class)]
sealed class TypeScriptModuleAttribute : Attribute
{
    private readonly string moduleName;
    public TypeScriptModuleAttribute(string moduleName)
    {
        this.moduleName = moduleName;
    }
}

```

allows you to 

```

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApplication1.Models
{
    [TypeScriptModule("TestThis")]
    public class SampleBase
    {
        public int MyProperty { get; set; }
    }

    [TypeScriptModule("TestThis")]
    public class SampleImpl : SampleBase
    {
        public int MyProperty2 { get; set; }
    }
}

```


to generate 
```

declare module TestThis {
	interface sampleBase {
		myProperty: number;
	}
	interface sampleImpl extends SampleBase {
		myProperty2: number;
	}
}

```

**Comment by raboud** [comment]
JsonProperty is also already recognized....but the Name Casing option can affect it.

**Comment by nhammadi** [comment]
@flcdrg I created a new setting called GlobalScope that should resolve this issue (Build 1.1.34)
