### ISSUE TITLE
Option to translate "Nullable" props in C# to "optional" props in TS

### ISSUE THREAD

**Issue by cyphercider** [madskristensen/TypeScriptDefinitionGenerator#15]
### Installed product versions
- Visual Studio: 2017
- This extension: 1.0.12

### Description
Sometimes it would be nice to automatically translate nullable class properties to optional interface properties.  I already have a code change that will do this, so if you like the idea I will submit a PR.

#### For example, translate:

public class ItemHeaderDto
    {
        **public int? Id { get; set; }**
        public string Name { get; set; } //
        public string Description { get; set; } //
    }

interface ItemHeaderDto{
		**Id?: number;**
		Name: string;
		Description: string;
	}

### Steps to recreate
1. Use extension version 1.0.12 to convert optional C# class property to a typescript interface

### Current behavior
Translates all attributes to required regardless of nullability in class

### Expected behavior
Automatically translate "nullable" c# props to "optional" interface props

**Comment by raboud** [comment]
The latest build from ci should fix this

**Comment by raboud** [comment]
Please Try Build 1.1.24 to see if your issues are corrected.

**Comment by nhammadi** [comment]
@madskristensen issue resolved, you should close this issue
