### ISSUE TITLE
Cannot create .d.ts for derived classes

### ISSUE THREAD

**Issue by mbreaton** [madskristensen/TypeScriptDefinitionGenerator#20]
### Installed product versions
- Visual Studio: [example 2017 Community]
- This extension: [example 1.0.16]
- ASP.Net Core 1.1 project

### Description
Cannot generate .d.ts with derived classes

### Steps to recreate
1. create file sample.cs:
    public class SampleBase
    {
        public int MyProperty { get; set; }
    }

    public class SampleImpl : SampleBase
    {
        public int MyProperty2 { get; set; }
    }
2. generate typescript definition

### Current behavior
Throws exception

### Expected behavior
Generate proper .d.ts file  

stepping through the code, the following line throws exception:

IntellisenseParser.cs:86
                if (baseClass != null && !underProcess.Contains(baseClass) && !HasIntellisense(baseClass.ProjectItem, references))

bacuse baseClass.ProjectItem throws COM Exception:
"Error HRESULT E_FAIL has been returned from a call to a COM component."

Seems related to #6

**Comment by raboud** [comment]
Please Try Build 1.1.24 to see if your issues are corrected.

**Comment by mbreaton** [comment]
Yes, this seems to have resolved the issue - thanks! I do however see a problem with the camel case of the base class and another with the eventName format in Telemetry. See comparison:  https://github.com/madskristensen/TypeScriptDefinitionGenerator/compare/master...mbreaton:master

**Comment by raboud** [comment]
I would close this issue and open another then put in a pull request referencing the new issue as it seems you have it identified and fixed
