### ISSUE TITLE
Problem installing extension on VS Community Edition 2015

### ISSUE THREAD

**Issue by dmorosinotto** [madskristensen/TypeScriptDefinitionGenerator#3]
### Installed product versions
- Visual Studio: Community 2015 v.14.0.25431.01 Update 3
- This extension: v.1.0.10

### Description
Try to install this extension on Visual Studio Community 2015 but the VSIX install doesn't work and report an error, see log attached.

### Steps to recreate
1. Download vsix from [marketplace](https://visualstudiogallery.msdn.microsoft.com/7ef40759-8802-4b48-b4d6-3c250fb4916e/file/241586/3/TypeScript%20Definition%20Generator%20v1.0.10.vsix)
2. Run it to install
3. Installation error wirh reported log details

### Current behavior
The installation fail reporting this message: The installation is not installable on any currently installed product.

### Expected behavior
Is it possible to install this extension on the Community Edition or it is only available for the official Visual Studio PRO+? 
I'd like to know if there are any technical reason not allowing to run it on the Community Edition, and possibly if you plan to support it in the future for the Community Edition, Thanks!

[VSIXInstaller_log.txt](https://github.com/madskristensen/TypeScriptDefinitionGenerator/files/716728/VSIXInstaller_log.txt)

**Comment by madskristensen** [comment]
From the log file it looks like the installer didn't find Visual Studio 2017. This extension only works on VS2017. Do you not have it installed?

**Comment by dmorosinotto** [comment]
Hi @madskristensen , no I've only VS2015 installed and I hadn't noticed that this is targeting only new VS2017, sorry my fault!

But is there any possibility that you can port this extension working even for VS2015 (and Community Edition) or there are some major technical problems for doing this?

**Comment by madskristensen** [comment]
Use Web Essentials 2015 instead. See this https://github.com/madskristensen/TypeScriptDefinitionGenerator/issues/2

**Comment by dmorosinotto** [comment]
Ok thanks, really appreciate your quick response!
