### ISSUE TITLE
Project Level Options

### ISSUE THREAD

**Issue by raboud** [madskristensen/TypeScriptDefinitionGenerator#31]
### Installed product versions
- Visual Studio: 2017 Professioinal
- This extension: 1.1.24

### Description
A project level override file for options. So all team members do not need to affect their global settings to produce a consistent output for the team. 

probably in JSON format.

could include output directory and project level module name.

**Comment by raboud** [comment]
@madskristensen i will work on this if you approve of it

**Comment by nhammadi** [comment]
@raboud you should start working on it and submit a PR

**Comment by raboud** [comment]
@nhammadi since it is a feature request not a bug, I would like to know Mads (the product owner) approves of the feature prior to working on it.

**Comment by madskristensen** [comment]
I love it. A .json file located in same folder or above overrides global settings

**Comment by raboud** [comment]
Is it okay to use Newtonsoft.Json. And can i update the nuget packages as there are a bunch of RC and PRE versions.

**Comment by madskristensen** [comment]
Yes, Newtonsoft.Json should be used for this

**Comment by raboud** [comment]
Got it in and working with one issue. If you change WebEssentials2015 it wont create the file....unless you turn off Generation then back on.

**Comment by raboud** [comment]
Need a second opinion....

at first i had the json file just override some options...thus allowing others to fall thru to the global settings.

on second thought that made no sense to me....project level setting seem to be an all or nothing - cant have half the team using one set of options and others using others. So I set the JSON file with the same default values as the Global Settings and marked all REQUIRED.

Opinions?

**Comment by madskristensen** [comment]
I agree. If local json file exist, global settings should be ignored

**Comment by raboud** [comment]
and make them all properties required?

**Comment by nhammadi** [comment]
@raboud if the local json file doesn't contain a property you should grab it's value from the global VS settings

**Comment by raboud** [comment]
@nhammadi that contradicts what I believe Mads is saying.

You cant really have half your team using one global option while the other half uses a different. example one using CamelCaseTypeNames true and one using CamelCaseTypeNames false. That would mess up inheritance.

**Comment by raboud** [comment]
@madskristensen So required or default values?

**Comment by styfle** [comment]
How about this scenario:

- User has TypeScriptDefinitionGenerator installed
- User has existing project using TypeScriptDefinitionGenerator v1.0 with json settings file
- TypeScriptDefinitionGenerator adds a new setting in v1.1
- TypeScriptDefinitionGenerator automatically updated on the user's machine
- User's existing project with a json settings file does not have this new setting
- User attempts to generate a `.d.ts` file
- What now?

Depending on the setting, it may or may not cause a problem.
So settings that are added that are backwards compatible can be optional.
But settings that are not backwards compatible should be required.
If a required setting is missing in the json, show an error for the user to correct and read the latest docs.

**Comment by raboud** [comment]
the way I have it currently coded...with required properties, the output will tell you there is an error in the json file and let you know the Json Exception message. Unfortunately it will stop processing at the first error, so if you are missing multiple required fields you will have to repeat for each missing property.

With Defaults it could get confusing if you had a different Global value set. Might be Difficult for user to understand why the Global is not used. I could output all the values being used. 

I already plan on outputting that a Project Level file is being used.
