### ISSUE TITLE
Can you generate a new release pls ?

### ISSUE THREAD

**Issue by valeriob** [madskristensen/TypeScriptDefinitionGenerator#41]
The current version seems to fix https://github.com/madskristensen/TypeScriptDefinitionGenerator/issues/40 https://github.com/madskristensen/TypeScriptDefinitionGenerator/issues/34
 and add the option file that is foundamental for team work.

**Comment by valeriob** [comment]
pretty pls ?

**Comment by madskristensen** [comment]
I'll spin up one now...

**Comment by madskristensen** [comment]
Ok, the build is done. Can you please help verify it works by downloading it from here? http://vsixgallery.com/extension/cad7b20b-4b83-4ca6-bf24-ca36a494241c/

When verified, I'll upload it to the marketplace. I've also added support for VS 2019 so it is ready for when the time comes.

**Comment by valeriob** [comment]
Thanks !
i've been using the ci build for many months now, it's fine ! But i do not have vs 2019 to test it 🛩

**Comment by madskristensen** [comment]
I just added background load which is required for VS 2019. Can you please test version 1.2.38 from here http://vsixgallery.com/extension/cad7b20b-4b83-4ca6-bf24-ca36a494241c/ in VS 2017?

**Comment by madskristensen** [comment]
I tested it and it worked on my machine so I decided to upload it to the marketplace
