### ISSUE TITLE
Dts package did not load correctly

### ISSUE THREAD

**Issue by Daniel-Prescience** [madskristensen/TypeScriptDefinitionGenerator#55]
### Installed product versions
- Visual Studio: 2019 Community + 2022 Preview
- This extension: 1.3.53

### Description
Extension works fine in VS2019, but I get the following error when trying to configure options for dts in VS2022:
![Dts-Error](https://user-images.githubusercontent.com/16936973/130062880-d4c67325-61f5-46f0-b154-241b182ca287.PNG)

Attached VS2022 activity log with an error description at the end of the file: 
[Dts-Error-VS2022-ActivityLog.log](https://github.com/madskristensen/TypeScriptDefinitionGenerator/files/7014096/Dts-Error-VS2022-ActivityLog.log)

### Steps to recreate
Go to "Generate d.ts" in VS options menu.
It's possible that the issue could be caused by having VS2022-preview installed alongside VS2019?

### Current behavior
Extension doesn't work.

### Expected behavior
Extension should work.

**Comment by BobSilent** [comment]
Same for me, it says in LOG:
```
LegacySitePackage failed for package [DtsPackage]
Source: 'mscorlib' 
Description: Could not load file or assembly 'Microsoft.VisualStudio.TextTemplating.VSHost.15.0, Version=16.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
```

**Comment by ericop** [comment]
same on VS2022 Pro (non-preview) for me. I uninstalled this extension and the modal popping up with that error each time I started my solution went away.

**Comment by StarNamer** [comment]
I also get his with VS2022 Pro Current. The extension was installed as part of the Dev Essentials package, but since we don't currently use TypeScript I'm quite happy to just uninstall this extension which sorts the error.

**Comment by valeriob** [comment]
Hi,
i confirm it's not working on vs 2022 :(

EDIT : i was able to make it work on Visual Studio 2022 with this changes : https://github.com/madskristensen/TypeScriptDefinitionGenerator/pull/57

**Comment by GeorgeLeithead** [comment]
Same problem for me, using Visual Studio 2022 Community Edition (64-bit), version 17.0.4.
I disabled this extension and re-loaded visual studio, and there was no error.

**Comment by BrianMinister** [comment]
Still having this problem on VS 2022 Ent Edition. 17.0.6

**Comment by itniels** [comment]
I have been seeing this issue as well also on the latest 17.1.0.
Is there a solution for it in the near future @madskristensen?

**Comment by daedalus-codes** [comment]
I too am seeing this error in VS2022.  A DDG search brought me here essentially. 

Regarding PR #57:

Could we create a new .csproj specifically for VS2022, have it reference the same files but point to the VS2022 SDK & editor requirements and it's own [source.extension.vsixmanifest](https://github.com/madskristensen/TypeScriptDefinitionGenerator/blob/master/src/source.extension.vsixmanifest).  Should separate vsix packages be generated or is there a way to include the projects together in a single vsix package somehow? 

TBH: I consider myself a VS extension noob as I have only dabbled with VS extension development.  In addition I haven't really looked into how other projects may have resolved a similar issue or what recommendation(s) would be.  (I know my lack of experience is showing lol).

**Comment by valeriob** [comment]
I wish i was able to do more, i'm not familiar with the process to package a new extension unfortunatly, i would really prefer @madskristensen to do it.

**Comment by daedalus-codes** [comment]
@valeriob, Thanks for a taking a shot at this issue!  tbh, I wouldn't mind chipping in myself.  

@madskristensen, when you get a moment, if you have any specific direction/recommendations, I'm sure we'll figure out a way resolve this issue while maintaining backward compatibility.  My "gut feeling" is that maintaining backward compatibility is key.
