### ISSUE TITLE
Should be disabled by default

### ISSUE THREAD

**Issue by johnciliberti** [madskristensen/TypeScriptDefinitionGenerator#8]
### Installed product versions
- Visual Studio: 2017 Community
- This extension: Latest version was installed by the Web Extension Pack 2017 

### Description
Every time I change a class, I am getting a .ts file created automatically. Since I did not manually install this add-on, I did not expect this behavior. **I recommend you remove this tool from your Web Extension pack until make the following changes**: 

1. Don't generate anything by default
2. Allow developer to enable either manually via right click context menu on a class or right click to enble for folder.

### Steps to recreate
1. Create or modify a class in Visual Studio 2017

### Current behavior
Generates a .ts file for all class files even controllers.

### Expected behavior
Only generate .ts files for the files or directories a developer specifies.

**Comment by LockTar** [comment]
I have the same issue in the latest VS2017 professional version. The extension is installed automatically and is automatically generating *.d.ts files. How can we stop the automatically generation process for **new** files but still enable the automatically generation of existing files.

**Comment by madskristensen** [comment]
This should be fixed in the latest version
