### ISSUE TITLE
The custom tool 'DtsGenerator' failed.

### ISSUE THREAD

**Issue by mhsimkin** [madskristensen/TypeScriptDefinitionGenerator#9]
### Installed product versions
- Visual Studio: 2017 Enterprise
- This extension:1.0.12

### Description
I tried to generate the *.d.ts file from a few of my C# classes. I received the error message "The custom tool 'DtsGenerator' failed.

### Steps to recreate
1. Right click on C# file
2. Select "Generate TypeScript Definition"
3. Find green line under file
4. Hover over line to see error message.

### Current behavior
No file generated. No detailed reason as to what caused DtsGenerator to fail.

### Expected behavior
I would like to see why the generation failed.  I would also like to see the generated file.

Sample Classes:
`
using System.ComponentModel.DataAnnotations;
using Microsoft.AspNet.Identity;
using Newtonsoft.Json;

namespace ClaimsManager.Models.UI
{
    public class WindowsAccount
    {
        [Required]
        public string UserName { get; set; }

        [Required]
        public string Domain { get; set; }

        [JsonIgnore]
        public string WindowsUserID => $"{Domain}\\{UserName}";

        [JsonIgnore]
        public UserLoginInfo UserLogin => new UserLoginInfo("Windows", WindowsUserID);
    }
}

using System;
using IdentityServer3.EntityFramework.Entities;
using Newtonsoft.Json;

namespace ClaimsManager.Models.UI.IdentityServer
{
    public class WebClient : Client
    {
        public Uri Url => new Uri($"/clients/{this.ClientId}", UriKind.Relative);

        // I'm using conditional property serialization to prevent the collections
        // from being sent to the client.
        [JsonIgnore]
        public bool ShouldSerializeClientSecrets { get; } = false;

        [JsonIgnore]
        public bool ShouldSerializeRedirectUris { get; } = false;

        [JsonIgnore]
        public bool ShouldSerializePostLogoutRedirectUris { get; } = false;

        [JsonIgnore]
        public bool ShouldSerializeAllowedScopes { get; } = false;

        [JsonIgnore]
        public bool ShouldSerializeIdentityProviderRestrictions { get; } = false;

        [JsonIgnore]
        public bool ShouldSerializeAllowedCustomGrantTypes { get; } = false;

        [JsonIgnore]
        public bool ShouldSerializeAllowedCorsOrigins { get; } = false;
    }

    public class GridWebClient
    {
        public int Id { get; set; }
        public bool Enabled { get; set; }
        public string ClientId { get; set; }
        public string ClientName { get; set; }
        public Uri Url => new Uri($"/clients/{this.ClientId}", UriKind.Relative);
    }
}
`

**Comment by mhsimkin** [comment]
I can't seem to attach a ZIP file.  If you provide an email I would be happen to send them.

Thanks

marc

**Comment by raboud** [comment]
This is actually an error in EnvDTE - the EnvDTE is throwing an error when trying to get the property Access Modifier when the property uses Expression-bodied Members.

I have wrapped the calls in some try catches but am still failing (with DTE Exceptions) when I traverse into the Client class.

Not sure where or how to post bug report for EnvDTE. 

On an aside - is WebClient really an entity that you want to pass to the Front End code?

**Comment by mhsimkin** [comment]
WebClient is just want I'm calling the class.  It has no relation to the .NET WebClient.

**Comment by raboud** [comment]
but its derived from Client where is client defined....in my test app I was getting it from Identity Server which is obviously wrong. Very Bad Assumption on MY part.

**Comment by mhsimkin** [comment]
The client class is from IdentityServer3.EntityFramework.
